### ISSUE TITLE
 Numbers in a domain name

### ISSUE THREAD

**Issue by prom1r** [Hypercontext/linkifyjs#384] opened 2022-04-18 14:26 UTC
Good afternoon, there was such a problem, if only numbers are present in the domain name 
( test@123.com ) then the link to the client's mail is not created correctly.

At this point 
https://github.com/Hypercontext/linkifyjs/blob/3eb5b8aacc286e57e220cd6ce2d9c139d96e7322/packages/linkify-react/src/linkify-react.js#L13 split into two objects, while with a normal link it should be one object, this leads to the problem
<img width="210" alt="Снимок экрана 2022-04-18 в 4 59 42 PM" src="https://user-images.githubusercontent.com/87613000/163821744-25b8318b-8646-44f8-87c7-499d65c173c8.png"> => not created correctly
<img width="315" alt="Снимок экрана 2022-04-18 в 4 59 32 PM" src="https://user-images.githubusercontent.com/87613000/163821740-f6f39dc2-06d3-4747-85a0-20c756600ae8.png"> => created correctly

**Comment by nfrasser** [comment] 2022-04-18 14:43
@prom1r what version of linkify are you using? I can't reproduce this in the latest v3.0.5

**Comment by prom1r** [comment] 2022-04-18 14:46
@nfrasser 2.1.9
Maybe it's fixed with some update?

**Comment by nfrasser** [comment] 2022-04-18 14:47
Yes, this is fixed in v3.0. Please update.

**Closed by nfrasser** 2022-04-18 14:47 UTC

**Comment by prom1r** [comment] 2022-04-18 14:48
Oh, thanks a lot
